name: Build APK using Docker (Buildozer)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Buildozer Docker Image to Build APK
        run: |
          sudo apt update
          sudo apt install -y docker.io
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd kivy/buildozer bash -c "
            cd /home/user/hostcwd &&
            pip install -r requirements.txt || true &&
            buildozer android debug
          "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: forsa_ps-apk
          path: bin/*.apk
