name: Build APK for Forsa_PS App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev libgles2-mesa-dev
          pip install buildozer cython kivy pyrebase4

      - name: Initialize Buildozer
        run: |
          buildozer init || echo "Buildozer already initialized"

      - name: Modify buildozer.spec
        run: |
          sed -i 's/^requirements = .*/requirements = python3,kivy,pyrebase4/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = forsa_ps/' buildozer.spec
          sed -i 's/^package.domain = .*/package.domain = org.forsa.ps/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: forsa_ps-apk
          path: bin/*.apk
